### ISSUE TITLE
Choose Styles in Dropdown

### ISSUE THREAD

**Issue by jdittrich** [JohnMcLear/ep_custom_styles#1]
Is it possible to re-access created styles via a list and/or to integrate custom_styles with [headings](https://github.com/fourplusone/etherpad-plugins)?
Mockup:
![dropdownMockup](http://i.imgur.com/8Moyywy.png?1)

**Comment by JohnMcLear** [comment]
Yea of course, afaik this already exists no?  If not it'd be easy enough to add it..
